apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool
  namespace: test
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: http-port-nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-port-multitool
      protocol: TCP
      port: 1180
      targetPort: 1180
    - name: https-port-multitool
      protocol: TCP
      port: 11443
      targetPort: 11443
