apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-init
  namespace: test
spec:
  selector:
    app: nginx-init
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 80
