apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      initContainers:
        - name: wait-for-service
          image: busybox
          command: [
              "sh",
              "-c",
              '
              until nslookup svc-nginx-init.test.svc.cluster.local; do
              echo "Waiting for service to start...";
              sleep 2;
              done;
              echo "Service is ready!"
              ',
            ]
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
